image:
  - Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.13\msvc2017_64\bin
  - set PYDIR=C:\Python36
  - set GODIR=C:\go113
  - set MINGWDIR=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  - set PATH=%QTDIR%;%PYDIR%;%GODIR%;%MINGWDIR%;%PATH%;
  - git submodule update --init

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvarsall.bat x86_amd64

build_script:
  - python install_dependency.py
  - cd clashr && python build_clashr.py
  - cd .. && mkdir build && cd build
  - qmake ../
  - nmake
  - cd ..
  - python release.py

artifacts:
- path: build\ShadowClash-windows.zip
  name: ShadowClash

deploy:
  provider: GitHub
  description: "ShadowClash Release"
  auth_token:
    secure: uAMRAuhJjhHbPRvsKDUGYBDrrDPhlj2q1zHICgjSo7K2CSmVMxHreSMJYqer4y2k
  artifact: ShadowClash
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
