image:
  - Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.13.0\msvc2017_64
  - set PYDIR=C:\Python36
  - set GODIR=C:\go113
  - set PATH=%QTDIR%\bin;%PYDIR%;%GODIR%;%PATH%;
  - git submodule update --init

build_script:
  - python install_dependency.py
  - cd clash && python build_clash.py
  - cd .. && mkdir build && cd build
  - qmake ../
  - nmake

deploy:
  provider: GitHub
  description: "ShadowClash Release"
  auth_token:
    secure: uAMRAuhJjhHbPRvsKDUGYBDrrDPhlj2q1zHICgjSo7K2CSmVMxHreSMJYqer4y2k
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
