image:
  - Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.13.0\msvc2017_64
  - set PYDIR=C:\Python36
  - set GODIR=C:\go113
  - set PATH=%QTDIR%\bin;%PYDIR%;%GODIR%;%PATH%;
  - ps: $goDistPath = "$env:TEMP\go1.13.3.windows-amd64.zip"
  - ps: (New-Object Net.WebClient).DownloadFile('https://dl.google.com/go/go1.13.3.windows-amd64.zip', $goDistPath)
  - ps: 7z x $goDistPath -oC:\go1133-x64 | Out-Null
  - ps: [IO.Directory]::Move('C:\go1133-x64\go', 'C:\go113')
  - ps: Remove-Item 'C:\go1133-x64' -Recurse -Force
  - ps: del $goDistPath
  - git submodule update --init

build_script:
  - python install_dependency.py
  - cd clash && python build_clash.py
  - cd .. && mkdir build && cd build
  - qmake ../
  - nmake

deploy:
  provider: GitHub
  description: "ShadowClash Release"
  auth_token:
    secure: uAMRAuhJjhHbPRvsKDUGYBDrrDPhlj2q1zHICgjSo7K2CSmVMxHreSMJYqer4y2k
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
