language: cpp

matrix:
  include:
    - os: osx
      env: BADGE=osx
    - os: linux
      dist: bionic
      sudo: required
      env: BADGE=linux

before_install:
  - if [ "$BADGE" = "linux" ]; then    sudo apt-get update; fi
  - if [ "$BADGE" = "osx"]; then
      sudo curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci;
      sudo source ./macports-ci install;
    fi

install:
  - if [ "$BADGE" = "linux" ]; then    
      sudo apt-get install qtchooser libgl-dev qt5-default qttools5-dev-tools python3.6 qtwebengine5-dev;
      sudo wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz;
      sudo tar -xvf go1.13.1.linux-amd64.tar.gz;
      sudo mv go /usr/local;
      export GOROOT=/usr/local/go;
      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
    fi
  - if [ "$BADGE" = "osx" ]; then
      export QT_MACPORTS=true;
      sudo port -b install qt5 qt5-qtcharts qt5-qtdatavis3d qt5-qtpurchasing qt5-qtremoteobjects qt5-qtscript qt5-qtwebglplugin qt5-qtwebengine qt5-qtwebview;
    fi

script:
  - git submodule update --init
  - bash install_dependency.sh
  - cd clash && python3 build_clash.py
  - cd ..
  - mkdir build && cd ./build
  - qmake ../
  - make -j8

defore_deplot:
  - if [[ $BADGE == "osx" ]]; then
      macdeployqt ShadowCoel.app;
      macdeployqt ShadowCoel.app -dmg;
    fi

deploy:
  provider: release
  api_key: $GIT_REPO_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true