language: cpp

matrix:
  include:
    - os: osx
      env: BADGE=osx
    - os: linux
      dist: bionic
      sudo: required
      env: BADGE=linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.13.2-bionic'
          packages:
            - qt513base
            - qt513tools
            - qt513declarative
            - qt513location
            - qt513quickcontrols2
            - qt513webchannel
            - qt513webengine
            - qt513x11extras
            - qt513translations
            - qt513scxml
            - qt513script

before_install:
  - if [ "$BADGE" = "linux" ]; then    sudo apt-get update; fi
  - if [ "$BADGE" = "osx" ]; then
      brew update;
    fi

install:
  - if [ "$BADGE" = "linux" ]; then    
      sudo apt-get install libgl-dev python3.6;
      sudo wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz;
      sudo tar -xvf go1.13.1.linux-amd64.tar.gz;
      sudo mv go /usr/local;
      export GOROOT=/usr/local/go;
      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
    fi
  - if [ "$BADGE" = "osx" ]; then    
      brew upgrade go --verbose;
      brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/89bf3a54383d884f8b8511c6237325dd5b5ae6ba/Formula/qt.rb --verbose;
    fi

before_script:
  - if [ "$BADGE" = "osx" ];   then    export PATH="/usr/local/Cellar/qt/5.13.1/bin:$PATH"; fi

script:
  - git submodule update --init
  - python3 install_dependency.py
  - cd clash && python3 build_clash.py
  - cd ..
  - mkdir build && cd ./build
  - qmake ../
  - make -j8

defore_deplot:
  - cd ..
  - python3 release.py

deploy:
  provider: release
  file: "ShadowClash-$BADGE.zip"
  api_key: $GIT_REPO_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true